/*
*  Copyright (c) 2019. All right reserved
* Created on 2023-07-26 ( Date ISO 2023-07-26 - Time 21:42:57 )
* Generated by Telosys Tools Generator ( version 4.0.0 )
*/
package org.demo.service;
import org.demo.entities.Car;
import org.springframework.data.domain.Page;
import org.springframework.data.domain.Pageable;
import org.springframework.data.jpa.domain.Specification;

import java.util.List;

/**
 * Service Interface for managing {@link Car}.
*  @author aek
 */
public interface CarService  {
   
    /**
     * create new item for domain
     *
     * @param entity entity to save.
     * @return persisted entity Car
     */
    Car create(Car d);

    /**
     * Update entity. Check before if existing data. If data is empty throw Exception
     *
     * @param entity domain
     * @param id of entity
     * @return Car
     */
    Car update(Car d);

    /**
     * get Car by id. Can be return empty
     *
     * @param id the id of the entity.
     * @return Car
     */
    Car getOne(int id) ;

    /**
     * Get all entities
     *
     * @return list of entities List<Car>
     */
    List<Car> getAll();

    /**
     * Count item in entity
     *
     * @return long 
     */
    long getTotal();

    /**
     * Delete record by id
     *  
     */
    void delete(int id);

    /**
     * Find all with pagination
     *
     * @return Page<Car>  
     */
    Page<Car> findAllPaginate(Pageable pageable);

    /**
     * Find all with pagination  by criteria 
     *
     * @return Page<Car>  
     */
	Page<Car> findAllSpecification(Specification<Car> specs, Pageable pageable);

}
