/*
*  Copyright (c) 2019. All right reserved
* Created on 2023-08-05 ( Date ISO 2023-08-05 - Time 10:29:13 )
* Generated by Telosys Tools Generator ( version 4.0.0 )
*/
package org.demo.service;


import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;
import org.demo.repositories.FabricanteRepository;
import org.demo.entities.Fabricante;
import org.demo.service.FabricanteService;
import org.springframework.data.domain.Page;
import org.springframework.data.domain.Pageable;
import org.springframework.data.jpa.domain.Specification;


import java.util.Collections;
import java.util.List;

/**
 * Service Implementation for managing {@link Fabricante}.
 * @author aek
 */
@Service
@Transactional
public class FabricanteServiceImpl implements FabricanteService {


    private final FabricanteRepository repository;

    public FabricanteServiceImpl(FabricanteRepository repo) {
         this.repository = repo;
    }


    /**
     * {@inheritDoc}
     */
    @Override
    public Fabricante create(Fabricante d) {
        try {
            return repository.save(d);

        } catch (Exception ex) {
            return null;
        }
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Fabricante update(Fabricante d) {
        try {
            return repository.saveAndFlush(d);

        } catch (Exception ex) {
            return null;
        }
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Fabricante getOne(int id) {
        try {
            return repository.findById(id).orElse(null);

        } catch (Exception ex) {
            return null;
        }
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<Fabricante> getAll() {
        try {
            return repository.findAll();

        } catch (Exception ex) {
            return Collections.emptyList();
        }
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public long getTotal() {
        try {
            return repository.count();
        } catch (Exception ex) {
            return 0;
        }
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public void delete(int id) {
        repository.deleteById(id);
    }

    /**
     * {@inheritDoc}
     */
   	@Override
	public Page<Fabricante> findAllPaginate(Pageable pageable) {

		return repository.findAll(pageable);
	}

    /**
     * {@inheritDoc}
     */
    @Override
	public Page<Fabricante> findAllSpecification(Specification<Fabricante> specs, Pageable pageable) {
		return repository.findAll(specs, pageable);
	}

}
