/*
*  Copyright (c) 2019. All right reserved
* Created on 2023-08-05 ( Date ISO 2023-08-05 - Time 14:19:46 )
* Generated by Telosys Tools Generator ( version 4.0.0 )
*/
package org.demo.service;


import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;
import org.demo.repositories.MedicamentoRepository;
import org.demo.entities.Medicamento;
import org.demo.service.MedicamentoService;
import org.springframework.data.domain.Page;
import org.springframework.data.domain.Pageable;
import org.springframework.data.jpa.domain.Specification;


import java.util.Collections;
import java.util.List;

/**
 * Service Implementation for managing {@link Medicamento}.
 * @author aek
 */
@Service
@Transactional
public class MedicamentoServiceImpl implements MedicamentoService {


    private final MedicamentoRepository repository;

    public MedicamentoServiceImpl(MedicamentoRepository repo) {
         this.repository = repo;
    }


    /**
     * {@inheritDoc}
     */
    @Override
    public Medicamento create(Medicamento d) {
        try {
            return repository.save(d);

        } catch (Exception ex) {
            return null;
        }
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Medicamento update(Medicamento d) {
        try {
            return repository.saveAndFlush(d);

        } catch (Exception ex) {
            return null;
        }
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Medicamento getOne(int id) {
        try {
            return repository.findById(id).orElse(null);

        } catch (Exception ex) {
            return null;
        }
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<Medicamento> getAll() {
        try {
            return repository.findAll();

        } catch (Exception ex) {
            return Collections.emptyList();
        }
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public long getTotal() {
        try {
            return repository.count();
        } catch (Exception ex) {
            return 0;
        }
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public void delete(int id) {
        repository.deleteById(id);
    }

    /**
     * {@inheritDoc}
     */
   	@Override
	public Page<Medicamento> findAllPaginate(Pageable pageable) {

		return repository.findAll(pageable);
	}

    /**
     * {@inheritDoc}
     */
    @Override
	public Page<Medicamento> findAllSpecification(Specification<Medicamento> specs, Pageable pageable) {
		return repository.findAll(specs, pageable);
	}

}
