/*
*  Copyright (c) 2019. All right reserved
* Created on 2023-08-05 ( Date ISO 2023-08-05 - Time 14:19:46 )
* Generated by Telosys Tools Generator ( version 4.0.0 )
*/
package org.demo.service;
import org.demo.entities.Medicamento;
import org.springframework.data.domain.Page;
import org.springframework.data.domain.Pageable;
import org.springframework.data.jpa.domain.Specification;

import java.util.List;

/**
 * Service Interface for managing {@link Medicamento}.
*  @author aek
 */
public interface MedicamentoService  {
   
    /**
     * create new item for domain
     *
     * @param entity entity to save.
     * @return persisted entity Medicamento
     */
    Medicamento create(Medicamento d);

    /**
     * Update entity. Check before if existing data. If data is empty throw Exception
     *
     * @param entity domain
     * @param id of entity
     * @return Medicamento
     */
    Medicamento update(Medicamento d);

    /**
     * get Medicamento by id. Can be return empty
     *
     * @param id the id of the entity.
     * @return Medicamento
     */
    Medicamento getOne(int id) ;

    /**
     * Get all entities
     *
     * @return list of entities List<Medicamento>
     */
    List<Medicamento> getAll();

    /**
     * Count item in entity
     *
     * @return long 
     */
    long getTotal();

    /**
     * Delete record by id
     *  
     */
    void delete(int id);

    /**
     * Find all with pagination
     *
     * @return Page<Medicamento>  
     */
    Page<Medicamento> findAllPaginate(Pageable pageable);

    /**
     * Find all with pagination  by criteria 
     *
     * @return Page<Medicamento>  
     */
	Page<Medicamento> findAllSpecification(Specification<Medicamento> specs, Pageable pageable);

}
