/*
 * Java domain class for entity "Fabricante" 
 * Created on 2023-08-05 ( Date ISO 2023-08-05 - Time 10:29:13 )
 * Generated by Telosys Tools Generator ( version 4.0.0 )
 */
package org.demo.repositories;
import org.demo.entities.Fabricante;
import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.data.jpa.repository.JpaSpecificationExecutor;
import org.springframework.stereotype.Repository;

/**
 * <h2>FabricanteRepository</h2>
 *
 * createdAt : 2023-08-05 - Time 10:29:13
 * <p>
 * Description: Spring Data repository for the {@link Fabricante} entity.
 * 
 * @author aek
 */
@Repository
public interface FabricanteRepository  extends JpaRepository<Fabricante, int> , JpaSpecificationExecutor<Fabricante> {

}
