/*
 * Java domain class for entity "Medicamento" 
 * Created on 2023-08-05 ( Date ISO 2023-08-05 - Time 14:19:46 )
 * Generated by Telosys Tools Generator ( version 4.0.0 )
 */
package org.demo.repositories;
import org.demo.entities.Medicamento;
import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.data.jpa.repository.JpaSpecificationExecutor;
import org.springframework.stereotype.Repository;

/**
 * <h2>MedicamentoRepository</h2>
 *
 * createdAt : 2023-08-05 - Time 14:19:46
 * <p>
 * Description: Spring Data repository for the {@link Medicamento} entity.
 * 
 * @author aek
 */
@Repository
public interface MedicamentoRepository  extends JpaRepository<Medicamento, int> , JpaSpecificationExecutor<Medicamento> {

}
