/*
*  Copyright (c) 2019. All right reserved
* Created on 2023-08-05 ( Date ISO 2023-08-05 - Time 21:49:52 )
* Generated by Telosys Tools Generator ( version 4.0.0 )
*/
package org.demo.controller;

import org.demo.entities.FabricanteEntity;
import org.demo.service.FabricanteEntityService;


import org.springframework.http.HttpStatus;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.DeleteMapping;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.bind.annotation.PutMapping;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RestController;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import javax.validation.Valid;
import java.util.List;


/**
 * REST controller for managing {@link FabricanteEntity}.
 *
 * @author @aek
 */
@RestController
@RequestMapping("/api/fabricanteEntity")
public class FabricanteEntityController {

    private final Logger log = LoggerFactory.getLogger(FabricanteEntityController.class);
	
    private final FabricanteEntityService entityService;

 	public FabricanteEntityController (FabricanteEntityService entityService) {
		this.entityService = entityService;
	}

    /**
     * {@code POST  /fabricanteEntity} : Create a new fabricanteEntity.
     *
     * @param fabricanteEntity the fabricanteEntity to create.
     * @return the {@link ResponseEntity} with status {@code 201 (Created)} and with body the new fabricanteEntity.
     */
	@PostMapping()
	public ResponseEntity<FabricanteEntity> createFabricanteEntity(@RequestBody @Valid FabricanteEntity fabricanteEntity) {
         log.debug("REST request to save FabricanteEntity : {}", fabricanteEntity);
         return new ResponseEntity<>(entityService.create(fabricanteEntity), HttpStatus.CREATED);
    }

   /**
     * {@code PUT  /fabricanteEntity} : Updates an existing fabricanteEntity.
     *
     * @param fabricanteEntity the fabricanteEntity to update.
     * @return the {@link ResponseEntity} with status {@code 200 (OK)} and with body the updated fabricanteEntity,
     * or with status {@code 400 (Bad Request)} if the fabricanteEntity is not valid,
     * or with status {@code 500 (Internal Server Error)} if the fabricanteEntity couldn't be updated.
     */
    @PutMapping()
    public ResponseEntity<FabricanteEntity> updateFabricanteEntity(@Valid @RequestBody FabricanteEntity fabricanteEntity) {
        log.debug("REST request to update FabricanteEntity : {}", fabricanteEntity);
        FabricanteEntity result = entityService.update(fabricanteEntity);
        return ResponseEntity.ok().body(result);
    }

    /**
     * {@code GET  /fabricanteEntity} : get all the fabricanteEntitys.
     *
     * @return the {@link ResponseEntity} with status {@code 200 (OK)} and the list of fabricanteEntity in body.
     */

    @GetMapping()
    public ResponseEntity<List<FabricanteEntity>> getAllFabricanteEntity() {
	    log.debug("REST request to get all fabricanteEntitys");
        List<FabricanteEntity> lst = entityService.getAll();

        return new ResponseEntity<>(lst,HttpStatus.OK);
    }

    /**
     * {@code GET  /fabricanteEntity/:id} : get the "id" fabricanteEntity.
     *
     * @param id the id of the fabricanteEntity to retrieve.
     * @return the {@link ResponseEntity} with status {@code 200 (OK)} and with body the fabricanteEntity, or with status {@code 404 (Not Found)}.
     */
    @GetMapping(value = "/{id}")
    public ResponseEntity<FabricanteEntity> getOneFabricanteEntity(@PathVariable("id") int id) {
        log.debug("REST request to get FabricanteEntity : {}", id);
        FabricanteEntity e = entityService.getOne(id);

        return new ResponseEntity<>(e, HttpStatus.OK);
    }

  /**
     * {@code DELETE  /fabricanteEntity/:id} : delete the "id" fabricanteEntity.
     *
     * @param id the id of the fabricanteEntity to delete.
     * @return the {@link ResponseEntity} with status {@code 204 (NO_CONTENT)}.
     */
    @DeleteMapping("/{id}")
    public ResponseEntity<Void> deleteFabricanteEntity(@PathVariable("id") int id) {
        log.debug("REST request to delete FabricanteEntity : {}", id);
        entityService.delete(id);
        return new ResponseEntity<>(HttpStatus.NO_CONTENT);
    }

}
