/*
*  Copyright (c) 2019. All right reserved
* Created on 2023-08-05 ( Date ISO 2023-08-05 - Time 14:19:46 )
* Generated by Telosys Tools Generator ( version 4.0.0 )
*/
package org.demo.controller;

import org.demo.entities.Fabricante;
import org.demo.service.FabricanteService;


import org.springframework.http.HttpStatus;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.DeleteMapping;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.bind.annotation.PutMapping;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RestController;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import javax.validation.Valid;
import java.util.List;


/**
 * REST controller for managing {@link Fabricante}.
 *
 * @author @aek
 */
@RestController
@RequestMapping("/api/fabricante")
public class FabricanteController {

    private final Logger log = LoggerFactory.getLogger(FabricanteController.class);
	
    private final FabricanteService entityService;

 	public FabricanteController (FabricanteService entityService) {
		this.entityService = entityService;
	}

    /**
     * {@code POST  /fabricante} : Create a new fabricante.
     *
     * @param fabricante the fabricante to create.
     * @return the {@link ResponseEntity} with status {@code 201 (Created)} and with body the new fabricante.
     */
	@PostMapping()
	public ResponseEntity<Fabricante> createFabricante(@RequestBody @Valid Fabricante fabricante) {
         log.debug("REST request to save Fabricante : {}", fabricante);
         return new ResponseEntity<>(entityService.create(fabricante), HttpStatus.CREATED);
    }

   /**
     * {@code PUT  /fabricante} : Updates an existing fabricante.
     *
     * @param fabricante the fabricante to update.
     * @return the {@link ResponseEntity} with status {@code 200 (OK)} and with body the updated fabricante,
     * or with status {@code 400 (Bad Request)} if the fabricante is not valid,
     * or with status {@code 500 (Internal Server Error)} if the fabricante couldn't be updated.
     */
    @PutMapping()
    public ResponseEntity<Fabricante> updateFabricante(@Valid @RequestBody Fabricante fabricante) {
        log.debug("REST request to update Fabricante : {}", fabricante);
        Fabricante result = entityService.update(fabricante);
        return ResponseEntity.ok().body(result);
    }

    /**
     * {@code GET  /fabricante} : get all the fabricantes.
     *
     * @return the {@link ResponseEntity} with status {@code 200 (OK)} and the list of fabricante in body.
     */

    @GetMapping()
    public ResponseEntity<List<Fabricante>> getAllFabricante() {
	    log.debug("REST request to get all fabricantes");
        List<Fabricante> lst = entityService.getAll();

        return new ResponseEntity<>(lst,HttpStatus.OK);
    }

    /**
     * {@code GET  /fabricante/:id} : get the "id" fabricante.
     *
     * @param id the id of the fabricante to retrieve.
     * @return the {@link ResponseEntity} with status {@code 200 (OK)} and with body the fabricante, or with status {@code 404 (Not Found)}.
     */
    @GetMapping(value = "/{id}")
    public ResponseEntity<Fabricante> getOneFabricante(@PathVariable("id") int id) {
        log.debug("REST request to get Fabricante : {}", id);
        Fabricante e = entityService.getOne(id);

        return new ResponseEntity<>(e, HttpStatus.OK);
    }

  /**
     * {@code DELETE  /fabricante/:id} : delete the "id" fabricante.
     *
     * @param id the id of the fabricante to delete.
     * @return the {@link ResponseEntity} with status {@code 204 (NO_CONTENT)}.
     */
    @DeleteMapping("/{id}")
    public ResponseEntity<Void> deleteFabricante(@PathVariable("id") int id) {
        log.debug("REST request to delete Fabricante : {}", id);
        entityService.delete(id);
        return new ResponseEntity<>(HttpStatus.NO_CONTENT);
    }

}
