/*
*  Copyright (c) 2019. All right reserved
* Created on 2023-08-05 ( Date ISO 2023-08-05 - Time 21:49:52 )
* Generated by Telosys Tools Generator ( version 4.0.0 )
*/
package org.demo.controller;

import org.demo.entities.MedicamentoEntity;
import org.demo.service.MedicamentoEntityService;


import org.springframework.http.HttpStatus;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.DeleteMapping;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.bind.annotation.PutMapping;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RestController;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import javax.validation.Valid;
import java.util.List;


/**
 * REST controller for managing {@link MedicamentoEntity}.
 *
 * @author @aek
 */
@RestController
@RequestMapping("/api/medicamentoEntity")
public class MedicamentoEntityController {

    private final Logger log = LoggerFactory.getLogger(MedicamentoEntityController.class);
	
    private final MedicamentoEntityService entityService;

 	public MedicamentoEntityController (MedicamentoEntityService entityService) {
		this.entityService = entityService;
	}

    /**
     * {@code POST  /medicamentoEntity} : Create a new medicamentoEntity.
     *
     * @param medicamentoEntity the medicamentoEntity to create.
     * @return the {@link ResponseEntity} with status {@code 201 (Created)} and with body the new medicamentoEntity.
     */
	@PostMapping()
	public ResponseEntity<MedicamentoEntity> createMedicamentoEntity(@RequestBody @Valid MedicamentoEntity medicamentoEntity) {
         log.debug("REST request to save MedicamentoEntity : {}", medicamentoEntity);
         return new ResponseEntity<>(entityService.create(medicamentoEntity), HttpStatus.CREATED);
    }

   /**
     * {@code PUT  /medicamentoEntity} : Updates an existing medicamentoEntity.
     *
     * @param medicamentoEntity the medicamentoEntity to update.
     * @return the {@link ResponseEntity} with status {@code 200 (OK)} and with body the updated medicamentoEntity,
     * or with status {@code 400 (Bad Request)} if the medicamentoEntity is not valid,
     * or with status {@code 500 (Internal Server Error)} if the medicamentoEntity couldn't be updated.
     */
    @PutMapping()
    public ResponseEntity<MedicamentoEntity> updateMedicamentoEntity(@Valid @RequestBody MedicamentoEntity medicamentoEntity) {
        log.debug("REST request to update MedicamentoEntity : {}", medicamentoEntity);
        MedicamentoEntity result = entityService.update(medicamentoEntity);
        return ResponseEntity.ok().body(result);
    }

    /**
     * {@code GET  /medicamentoEntity} : get all the medicamentoEntitys.
     *
     * @return the {@link ResponseEntity} with status {@code 200 (OK)} and the list of medicamentoEntity in body.
     */

    @GetMapping()
    public ResponseEntity<List<MedicamentoEntity>> getAllMedicamentoEntity() {
	    log.debug("REST request to get all medicamentoEntitys");
        List<MedicamentoEntity> lst = entityService.getAll();

        return new ResponseEntity<>(lst,HttpStatus.OK);
    }

    /**
     * {@code GET  /medicamentoEntity/:id} : get the "id" medicamentoEntity.
     *
     * @param id the id of the medicamentoEntity to retrieve.
     * @return the {@link ResponseEntity} with status {@code 200 (OK)} and with body the medicamentoEntity, or with status {@code 404 (Not Found)}.
     */
    @GetMapping(value = "/{id}")
    public ResponseEntity<MedicamentoEntity> getOneMedicamentoEntity(@PathVariable("id") int id) {
        log.debug("REST request to get MedicamentoEntity : {}", id);
        MedicamentoEntity e = entityService.getOne(id);

        return new ResponseEntity<>(e, HttpStatus.OK);
    }

  /**
     * {@code DELETE  /medicamentoEntity/:id} : delete the "id" medicamentoEntity.
     *
     * @param id the id of the medicamentoEntity to delete.
     * @return the {@link ResponseEntity} with status {@code 204 (NO_CONTENT)}.
     */
    @DeleteMapping("/{id}")
    public ResponseEntity<Void> deleteMedicamentoEntity(@PathVariable("id") int id) {
        log.debug("REST request to delete MedicamentoEntity : {}", id);
        entityService.delete(id);
        return new ResponseEntity<>(HttpStatus.NO_CONTENT);
    }

}
