/*
*  Copyright (c) 2019. All right reserved
* Created on 2023-08-06 ( Date ISO 2023-08-06 - Time 09:55:41 )
* Generated by Telosys Tools Generator ( version 4.0.0 )
*/
package org.demo.controller;

import org.demo.entities.Pessoa;
import org.demo.service.PessoaService;


import org.springframework.http.HttpStatus;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.DeleteMapping;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.bind.annotation.PutMapping;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RestController;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import javax.validation.Valid;
import java.util.List;


/**
 * REST controller for managing {@link Pessoa}.
 *
 * @author @aek
 */
@RestController
@RequestMapping("/api/pessoa")
public class PessoaController {

    private final Logger log = LoggerFactory.getLogger(PessoaController.class);
	
    private final PessoaService entityService;

 	public PessoaController (PessoaService entityService) {
		this.entityService = entityService;
	}

    /**
     * {@code POST  /pessoa} : Create a new pessoa.
     *
     * @param pessoa the pessoa to create.
     * @return the {@link ResponseEntity} with status {@code 201 (Created)} and with body the new pessoa.
     */
	@PostMapping()
	public ResponseEntity<Pessoa> createPessoa(@RequestBody @Valid Pessoa pessoa) {
         log.debug("REST request to save Pessoa : {}", pessoa);
         return new ResponseEntity<>(entityService.create(pessoa), HttpStatus.CREATED);
    }

   /**
     * {@code PUT  /pessoa} : Updates an existing pessoa.
     *
     * @param pessoa the pessoa to update.
     * @return the {@link ResponseEntity} with status {@code 200 (OK)} and with body the updated pessoa,
     * or with status {@code 400 (Bad Request)} if the pessoa is not valid,
     * or with status {@code 500 (Internal Server Error)} if the pessoa couldn't be updated.
     */
    @PutMapping()
    public ResponseEntity<Pessoa> updatePessoa(@Valid @RequestBody Pessoa pessoa) {
        log.debug("REST request to update Pessoa : {}", pessoa);
        Pessoa result = entityService.update(pessoa);
        return ResponseEntity.ok().body(result);
    }

    /**
     * {@code GET  /pessoa} : get all the pessoas.
     *
     * @return the {@link ResponseEntity} with status {@code 200 (OK)} and the list of pessoa in body.
     */

    @GetMapping()
    public ResponseEntity<List<Pessoa>> getAllPessoa() {
	    log.debug("REST request to get all pessoas");
        List<Pessoa> lst = entityService.getAll();

        return new ResponseEntity<>(lst,HttpStatus.OK);
    }

    /**
     * {@code GET  /pessoa/:id} : get the "id" pessoa.
     *
     * @param id the id of the pessoa to retrieve.
     * @return the {@link ResponseEntity} with status {@code 200 (OK)} and with body the pessoa, or with status {@code 404 (Not Found)}.
     */
    @GetMapping(value = "/{id}")
    public ResponseEntity<Pessoa> getOnePessoa(@PathVariable("id") int id) {
        log.debug("REST request to get Pessoa : {}", id);
        Pessoa e = entityService.getOne(id);

        return new ResponseEntity<>(e, HttpStatus.OK);
    }

  /**
     * {@code DELETE  /pessoa/:id} : delete the "id" pessoa.
     *
     * @param id the id of the pessoa to delete.
     * @return the {@link ResponseEntity} with status {@code 204 (NO_CONTENT)}.
     */
    @DeleteMapping("/{id}")
    public ResponseEntity<Void> deletePessoa(@PathVariable("id") int id) {
        log.debug("REST request to delete Pessoa : {}", id);
        entityService.delete(id);
        return new ResponseEntity<>(HttpStatus.NO_CONTENT);
    }

}
